### PR TITLE
Add GitHub Actions scripts for CI, deploy and report-coverage

### PR DESCRIPTION
**Pull request by nihonjinrxs**
Does what it says on the tin.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205522639319327

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
I'll note that these actions make use of `actions/checkout@v2` and `actions/cache@v2`, which throw warnings on every build about a node 12 dependency. The [origin for these workflows](https://github.com/mbta/.github/blob/main/workflow-templates/elixir.yml#L37-L39) still does that, so I've left it here, but I think it would be a good idea to consider upgrading our actions scripts to use the latest versions, `actions/checkout@v4` and `actions/cache@v3`.
cc @paulswartz

**Comment by nihonjinrxs** [comment]
The test failure happening here should be fixed in #2.

**Comment by paulswartz** [comment]
@nihonjinrxs thanks for letting us know! You should feel free to update the versions here.

**Comment by nihonjinrxs** [comment]
This is ready for review, but we'll hold on merging it until [the Terraform stuff happening here to create the deploy environments](https://github.com/mbta/devops/pull/1273) is done.

**Review by krisrjohnson21 — APPROVED** [review]
🧼

**Pull request merged**
